export const expenses = [
  {
    id: '1903823435',
    description: 'descrição 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'saúde',
    value: 34.50,
    date: '2020-10-12',
    paid: true,
    reminderCreated: null,
  },
  {
    id: '3qwe20e20ek23e0',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'saúde',
    value: 3244.00,
    date: '2020-10-13',
    paid: true,
    reminderCreated: null,
  },
  {
    id: '1204932rfk09e3erk',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'lazer',
    value: 125.30,
    date: '2020-10-12',
    paid: false,
    reminderCreated: null,
  },
  {
    id: '21039i2m-23i',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'saúde',
    value: 12.34,
    date: '2020-10-14',
    paid: true,
    reminderCreated: null,
  },
  {
    id: '21039i2m3i',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 1235.34,
    date: '2020-10-14',
    paid: false,
    reminderCreated: '2020-11-22',
  },
  {
    id: '21039i3i',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 244.05,
    date: '2020-10-15',
    paid: false,
    reminderCreated: '2020-11-12',
  },
  {
    id: '239i2m3i',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 214.15,
    date: '2020-10-15',
    paid: false,
    reminderCreated: null,
  },
  {
    id: 'asd233i',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 214.15,
    date: '2020-10-16',
    paid: true,
    reminderCreated: null,
  },
  {
    id: 'asd239i2m3i',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 2124.15,
    date: '2020-10-17',
    paid: false,
    reminderCreated: null,
  },
  {
    id: 'asd239i2di',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 124.15,
    date: '2020-10-17',
    paid: false,
    reminderCreated: '2020-10-19',
  },
  {
    id: 'asd23di',
    description: 'descriçãoasfsad sdf das fsd 1 do lembrete e tals lorem ipsum dolor amet',
    tag: 'alimentação',
    value: 1124.10,
    date: '2020-10-18',
    paid: true,
    reminderCreated: null,
  },
];

export const tags = ['saúde', 'lazer', 'alimentação'];